Vue.component("footer-link", {
  template: [
    ' <div id="footer">',
    ' <div id="footer-top">',
    ' <div id="footer-logo"><img src="./static/image/1@2x.png" alt=""></div>',
    ' <div id="footer-link">',
    ' <a href="">学视分享</a><span>|</span>',
    ' <a href="coursewareSharing.html">课件分享</a><span>|</span>',
    ' <a href="microLesson.html">微课资源</a><span>|</span>',
    '<a  href="liveBroadcastCourse.html"  target="_blank">课程直播</a><span>|</span>',
    '<a href="teacherSpace.html"  target="_blank">名师空间</a></div>',
    '</div>',
    '<div id="footer-center">',
    '<div id="footer-message">',
    '<ul>',
    '<li>免费热线：400-888-9999 </li>',
    '<li>传真：595-7777999</li>',
    '<li> 邮箱：ZSDR@163.com </li>',
    '<li>Copyright © 2018 - 2019</li>',
    '<li> 漳州市知书达人网络科技有限公司版权所有</li>',
    '<li>闽ICP备184848590号-1</li>',
    '<li>闽公网安备 11010802023134号</li>',
    '</ul>',
    '<div class="clr"></div>',
    '<div id="footer-message-logo"><img src="./static/image/39.svg" alt=""></div>',
    '</div>',
    '</div>',
    '<div id="footer-yqlj">',
    '<span>合作机构 / 友情链接</span>',
    '<a href=""><img src="./static/image/40.png" alt=""></a>',
    '<a href=""><img src="./static/image/41.png" alt=""></a>',
    '<a href=""><img src="./static/image/42.png" alt=""></a>',
    '<a href=""><img src="./static/image/43.png" alt=""></a>',
    '<a href=""><img src="./static/image/44.png" alt=""></a>',
    '<a href=""><img src="./static/image/40.png" alt=""></a>',
    '<a href=""><img src="./static/image/41.png" alt=""></a>',
    '<a href=""><img src="./static/image/42.png" alt=""></a>',
    '<a href=""><img src="./static/image/43.png" alt=""></a>',
    '<a href=""><img src="./static/image/44.png" alt=""></a>',
    '</div>',
    '</div>',
  ].join("")
})