Vue.component("header-course", {
  template: [
    ' <div class="header">',
    ' <div id="header-top">',
    ' <span>',
    '<a href="index.html">  <img src="./static/image/1@2x.png" alt="" id="logo"></a>',
    '  </span>',
    '<span id="header-top-right">',
    ' <img src="./static/image/2.svg" alt="">',
    ' <span>客服热线：155-0696-3353</span>',
    ' <span id="header-top-right-right"><span id="name">江</span>同学，欢迎您！您的账户还有<span id="jifen">1000</span>积分&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<img',
    '     src="./static/image/3.svg" alt=""><span><a>进入个人空间</a></span></span>',
    '  </span>',
    ' </div>',
    ' <div class="header-center">',
    ' <div>学习从来无捷径，循环渐进登高峰。</div>',
    '   </div>',
    ' <div id="header-seach">',
    '   <form action="">',
    '    <input type="text" placeholder="请输入搜索内容">',
    ' <button type="button">搜索</button>',
    ' </div>',
    ' <div id="course-choose">',
    ' <ul class="course-ul">',
    '<li>',
    '      <div class="course-choose-title">    <img src="./static/image/45.svg" alt="">小学课程</div>',
    '     <ul class="course-choose-content">',
    '  <li><a href="javascript:void(0);">语文</a></li>',
    '   <li><a href="javascript:void(0);">数学</a></li>',
    ' <li><a href="javascript:void(0);">英语</a></li>',
    ' <li><a href="javascript:void(0);">思想品德</a></li>',
    ' <li><a href="javascript:void(0);">体育</a></li>',
    ' <li><a href="javascript:void(0);">音乐</a></li>',
    '      <li><a href="javascript:void(0);">美术</a></li>',
    '  </ul>',
    '  </li>',
    ' <li>',
    '      <div class="course-choose-title">    <img src="./static/image/45.svg" alt="">初中课程</div>',
    '  <ul class="course-choose-content">',
    ' <li><a href="javascript:void(0);">语文</a></li>',
    '  <li><a href="javascript:void(0);">数学</a></li>',
    '  <li><a href="javascript:void(0);">英语</a></li>',
    ' <li><a href="javascript:void(0);">政治</a></li>',
    '  <li><a href="javascript:void(0);">历史</a></li>',
    '  <li><a href="javascript:void(0);">地理</a></li>',
    '  <li><a href="javascript:void(0);">生物</a></li>',
    '  <li><a href="javascript:void(0);">化学</a></li>',
    '  <li><a href="javascript:void(0);">物理</a></li>',
    '   <li><a href="javascript:void(0);">体育</a></li>',
    ' <li><a href="javascript:void(0);">音乐</a></li>',
    '  <li><a href="javascript:void(0);">美术</a></li>',
    ' </ul>',
    '   </li>',
    '  <li>',
    '   <div class="course-choose-title">    <img src="./static/image/45.svg" alt="">高中课程</div>',
    '    <ul class="course-choose-content">',
    ' <li><a href="javascript:void(0);">语文</a></li>',
    '  <li><a href="javascript:void(0);">数学</a></li>',
    '  <li><a href="javascript:void(0);">英语</a></li>',
    ' <li><a href="javascript:void(0);">政治</a></li>',
    '  <li><a href="javascript:void(0);">历史</a></li>',
    '  <li><a href="javascript:void(0);">地理</a></li>',
    '  <li><a href="javascript:void(0);">生物</a></li>',
    '  <li><a href="javascript:void(0);">化学</a></li>',
    '  <li><a href="javascript:void(0);">物理</a></li>',
    '   <li><a href="javascript:void(0);">体育</a></li>',
    ' <li><a href="javascript:void(0);">音乐</a></li>',
    '  <li><a href="javascript:void(0);">美术</a></li>',
    '  </ul>',
    '  </li>',
    ' </ul>',
    ' </div>',
    ' </div>',
  ].join("")
})
Vue.component("header-micro", {
  template: [
    ' <div class="header">',
    ' <div id="header-top">',
    ' <span>',
    ' <a href="index.html">  <img src="./static/image/1@2x.png" alt="" id="logo"></a>',
    '  </span>',
    '   <span id="header-top-right">',
    '  <img src="./static/image/2.svg" alt="">',
    ' <span>客服热线：155-0696-3353</span>',
    '          <span id="header-top-right-right"><span id="name">江</span>同学，欢迎您！您的账户还有<span id="jifen">1000</span>积分&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<img',
    '      src="./static/image/3.svg" alt=""><span><a>进入个人空间</a></span></span>',
    '  </span>',
    ' </div>',
    '<div class="header-center">',
    '        <div>学习从来无捷径，循环渐进登高峰。</div>',
    '   </div>',
    '      <div id="header-seach">',
    '       <form action="">',
    '      <input type="text" placeholder="请输入搜索内容">',
    '     <button type="button">搜索</button>',
    '   </div>',
    '  <div class="header-bottom-link">',
    '  <div class="header-bottom-container">',
    ' <div class="left-choose">',
    '   <span><a href="shareDetaile.html">首页</a></span>',
    '      <span><a href="">小学</a></span>',
    '  <span><a href="">初中</a></span>',
    '     <span><a href="">高中</a></span>',
    '     </div>',
    '      <div class="right-choose">',
    '      <span><a href=""><img src="./static/image/55.svg" alt="">学视分享</a></span>',
    '      <span><a href="coursewareSharing.html"><img src="./static/image/66.svg" alt="">课件分享</a></span>',
    '     <span><a href="microLesson.html"><img src="./static/image/77.svg" alt="">微课资源</a></span>',
    '          <span><a href="liveBroadcastCourse.html" target="_blank"><img src="./static/image/88.svg" alt="">课程直播</a></span>',
    '            <span><a href="teacherSpace.html" target="_blank"><img src="./static/image/99.svg" alt="">名师空间</a></span>',
    '     </div>',
    '  </div>',
    '     </div>',
    '   </div>'
  ].join("")
})
Vue.component("header-space", {
  template: [
    ' <div class="header">',
    ' <div class="headerTop">',
    '  <div class="headerLogo"><a href="index.html"> <img src="./static/image/1@2x.png" alt="" id="logo"></a></div>',
    '   <div class="headerInput">',
    '  <form action="">',
    '  <input type="text" name="" id="" placeholder="请输入搜索内容">',
    '  <button>搜索</button>',
    '   </form>',
    '  </div>',
    '   </div>',

    ' <div class="headerContent">',
    '<div>亲子共育的美好时光</div>',
    '  <div>您好，欢迎光临！一起开启亲子共育的美好旅程</div>',
    '   </div>',

    '  <div class="headerBottom">',
    '<ul>',
    '      <li><a href="teacherSpace.html"><img src="./static/image/555.svg" alt="">空间首页</a></li>',
    '       <li><a href="personArticle.html"><img src="./static/image/666.svg" alt="">文章</a></li>',
    '  <li><a href="resourceListManagement.html"><img src="./static/image/777.svg" alt="">资源</a></li>',
    '    <li><a href="album.html"><img src="./static/image/888.svg" alt="">相册</a></li>',
    '        <li><a href="messageBoard.html"><img src="./static/image/999.svg" alt="">留言板</a></li>',
    '     </ul>',
    '    </div>',
    '  </div>'
  ].join("")
})